#================================================
# api_services:
#   "서비스 이름": "불러올 서비스 클래스 이름"
#   ex) deep: DeepLTranslateAPI
#================================================


api_services:
  deepl: DeepLTranslateAPI
  google: GoogleTranslateAPI
  papago: NaverPapagoAPI

model_services:
  huggingface_nllb: HuggingFaceNllbModel
  torch_transformer: TorchTransformerModel


