#================================================
# 
#================================================


api_services:
  deepl: DeepLTranslateAPI
  google: GoogleTranslateAPI
  papago: NaverPapagoAPI

model_services:
  huggingface_nllb: HuggingFaceNllbModel



