# Workflow name
name: AI Translate and Suggestion Server Deploy

on:
  # Trigger on push or pull request to the main branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: create dotenv
        run: |
          touch .env
          echo "DEEPL_AUTH_KEY=${{ secrets.DEEPL_AUTH_KEY }}" > .env

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            # Check if the container is running
            if [ $(sudo docker ps -q -f name=${{ secrets.DOCKER_IMAGE_NAME }}) ]; then
              echo "Stopping and removing existing container..."
              sudo docker stop ${{ secrets.DOCKER_IMAGE_NAME }}
              sudo docker rm ${{ secrets.DOCKER_IMAGE_NAME }}
            fi

            # Remove any existing image
            if [ $(sudo docker images -q ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}) ]; then
              echo "Removing existing image..."
              sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
            fi

            # Pull the latest image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}

            # Run the new container
            sudo docker run --network=host -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name ${{ secrets.DOCKER_IMAGE_NAME }} \
            -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
